services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres
      - ./backend/database:/docker-entrypoint-initdb.d
    networks:
      - internal

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backend/keycloak/theme/test:/opt/keycloak/themes/test
    ports:
      - 8080:8080
    networks:
      - internal
      - public
    command:
      - start-dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - public
    depends_on:
      - gateway

  gateway:
    build: ./backend/gateway
    ports:
      - 3000:3000
    environment:
      - USERS_SERVICE_URL="http://users:8080"
      - CHATS_SERVICE_URL=http://chats:8080
    networks:
      - internal
      - public
    depends_on:
      #      - users
      - chats

  chats:
    build: ./backend/chats
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres/chats
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_RESOURCE=${KEYCLOAK_RESOURCE}
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - internal

#  users:
#    build: ./backend/users
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#    networks:
#      - internal

volumes:
  postgres_data:


networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
