services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: amon
      KEYCLOAK_ADMIN_PASSWORD: 123123
    volumes:
      - ./backend/keycloak/theme/test:/opt/keycloak/themes/test
    ports:
      - 8080:8080
    networks:
      - internal
      - public
    command: >
      start-dev  --http-enabled=true  --hostname-strict=false
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - public
    depends_on:
      - gateway
      - keycloak

  gateway:
    build: ./backend/gateway
    ports:
      - 3000:3000
    environment:
      - USERS_SERVICE_URL="http://users:8080"
      - CHATS_SERVICE_URL=http://chats:8080
    networks:
      - internal
      - public
    depends_on:
      - chats
      #      - users

  chats:
    build: ./backend/chats
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/chats
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_RESOURCE=${KEYCLOAK_RESOURCE}

      - KEYCLOAK_ADMIN_REALM=${KEYCLOAK_ADMIN_REALM}
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID}
      - KEYCLOAK_ADMIN_CLIENT_SECRET=${KEYCLOAK_ADMIN_CLIENT_SECRET}
    networks:
      - internal
    ports:
      - 3001:8080
    volumes:
      - ./backend/chats:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres
      - ./backend/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - internal

volumes:
  postgres_data:


networks:
  internal:
  public:
