services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - public
    volumes:
      - ../../frontend:/app
      - frontend_node_modules:/app/node_modules

  gateway:
    image: nginx:alpine
    ports:
      - 8080:80
    networks:
      - internal
      - public
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - users

  users:
    build: ../../backend/users
    ports:
      - 5005:5005
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/users
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET_BASE_64=${JWT_SECRET_BASE_64}
      - JWT_EXPIRATION_SECONDS=${JWT_EXPIRATION_SECONDS}
      - JWT_REFRESH_EXPIRATION_SECONDS=${JWT_REFRESH_EXPIRATION_SECONDS}
      - FRONTEND_URL=http://localhost:8080
    networks:
      - internal
    volumes:
      - ../../backend/users:/app
      - users_gradle_cache:/root/.gradle
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres
      - ../postgres:/docker-entrypoint-initdb.d
    networks:
      - internal

volumes:
  postgres_data:
  frontend_node_modules:
  gateway_node_modules:
  users_gradle_cache:
  chats_gradle_cache:


networks:
  internal:
  public:

    # chats:
    #   build: ./backend/chats
    #   environment:
    #     - POSTGRES_URL=jdbc:postgresql://postgres:5432/chats
    #     - POSTGRES_USER=${POSTGRES_USER}
    #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   networks:
    #     - internal
    #   volumes:
    #     - ./backend/chats:/app
    #     - chats_gradle_cache:/root/.gradle
    #   depends_on:
    #     - postgres


    # gateway:
    #   build: ./backend/gateway
    #   ports:
    #     - 8080:8080
    #   environment:
    #     - USERS_SERVICE_URL=http://users:8080
    #     - CHATS_SERVICE_URL=http://chats:8080
    #     - CORS_ORIGIN=http://localhost:3000
    #   networks:
    #     - internal
    #     - public
    #   volumes:
    #     - ./backend/gateway:/app
    #     - gateway_node_modules:/app/node_modules
    #   depends_on:
    #     # - chats
    #     - users
